# Generated by Django 3.1.4 on 2021-01-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lservice', '0002_auto_20210121_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='item_name',
        ),
    ]
